name: cv_maker
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.5.0=py311haa95532_0
  - annotated-types=0.6.0=py311haa95532_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.6.0=hd77b12b_0
  - arrow-cpp=21.0.0=h0399227_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=py311haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - blinker=1.9.0=py311haa95532_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.0.9.2=py311h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cachetools=5.5.1=py311haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h02ab6af_1
  - charset-normalizer=3.4.4=py311haa95532_0
  - click=8.2.1=py311haa95532_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=py311haa95532_0
  - gitpython=3.1.45=py311haa95532_0
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py311haa95532_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=py311haa95532_1
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6c2663c_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311haa95532_0
  - jiter=0.6.1=py311hefb1915_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.0=py311haa95532_1
  - jsonschema-specifications=2025.9.1=py311haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=h885b0b7_4
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=hc70643c_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.7.0=h404307b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - narwhals=2.7.0=py311haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.4=py311h050da96_1
  - numpy-base=2.3.4=py311h1e017a8_1
  - openai=1.109.1=py311haa95532_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.0=hf43e1a1_0
  - packaging=25.0=py311haa95532_1
  - pandas=2.3.3=py311h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py311h4212202_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=py311haa95532_1
  - protobuf=5.29.3=py311h5da7b33_0
  - psutil=7.1.3=py311hf893f09_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py311ha5e6156_0
  - pycparser=2.23=py311haa95532_0
  - pydantic=2.12.3=py311haa95532_1
  - pydantic-core=2.41.4=py311h114bc41_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py311haa95532_1
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311haa95532_0
  - pywin32=311=py311hefeebc8_1
  - pyyaml=6.0.2=py311h827c3e9_0
  - pyzmq=27.1.0=py311h7149c55_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py311haa95532_0
  - requests=2.32.5=py311haa95532_1
  - rpds-py=0.28.0=py311h114bc41_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - smmap=5.0.2=py311haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - streamlit=1.51.0=py311haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tenacity=9.1.2=py311haa95532_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.1=py311h827c3e9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=py311haa95532_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchdog=6.0.0=py311haa95532_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\fjgon\miniconda3\envs\cv_maker
